version: 2.1

jobs:
  build:
    docker:
     - image: ferozsalam/elastalert-ci:0.1.1
     - image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
       environment:
       - "discovery.type=single-node"
       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    working_directory: /data/tests/

    steps:
      - checkout
      - run: >-
            dockerize -wait http://localhost:9200 -timeout 120s
              python /data/elastalert-ci.py --data data-files.yaml --rules_directory /data/tests
