version: 2.1

jobs:
  build:
    docker:
     - image: ferozsalam/elastalert-unit:latest
     - image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
       environment:
       - "discovery.type=single-node"
       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    working_directory: /data

    steps:
      - checkout
      - run: dockerize -wait http://elasticsearch:9200 -timeout 120s elastalert-test-rule data.json --config config.yaml rule.yaml
